dt: 0.01
human_control_law: CONST_VEL
human_kynematic_model: KEYPOINTS
human_n_dof: 18
human_n_kpts: 18 # Number of keypoints (equal to human_n_dof if human_kynematic_model is KEYPOINTS)
human_noisy_model: False
human_noisy_measure: False
human_model_variances: [0.1 0.1 0.1     0.1 0.1 0.1     0.1 0.1 0.1]      # [pos, vel, acc] x human_n_dof
human_init_variances:  [1.0 10.0 100.0  1.0 10.0 100.0  1.0 10.0 100.0]   # [pos, vel, acc] x human_n_dof
robot_init_variances:  [0.01 0.01 0.1   0.01 0.01 0.1   0.01 0.01 0.1   0.01 0.01 0.1   0.01 0.01 0.1   0.01 0.01 0.1] # [pos, vel, acc] x robot_n_dof
human_Kp: 1.0
human_Kd: 1.0
human_K_repulse: 1.0
robot_control_law: TRAJ_FOLLOW
robot_n_dof: 6
alpha: 0.3
beta: 2.0
kappa: 0.1
skeleton_topic: "/zed/zed_node/body_trk/skeletons"
robot_js_topic: "/ur10/joint_states"
predicted_hri_state_topic: "/predicted_hri_state"
predicted_hri_cov_topic: "/predicted_hri_cov"
human_state_topic: "/human_state"
hz: 100
num_steps: 10