dt: 0.01
human_control_law: CONST_VEL
human_kynematic_model: KEYPOINTS
human_n_dof: 3    # Number of degrees of freedom (i.e., number of joints if human_kynematic_model is KYN_CHAIN)
human_n_kpts: 18  # Number of keypoints (equal to human_n_dof if human_kynematic_model is KEYPOINTS)
human_noisy_model: True
human_noisy_measure: True
human_meas_variance: # Measurement noise for each human keypoint (Hip: all keypoints have the same variance)
  x:
    pos: 0.1
    vel: 1.0
  y:
    pos: 0.1
    vel: 1.0
  z:
    pos: 0.1
    vel: 1.0
human_model_variance: # Model uncertainty for each human DoF
    pos: 0.1
    vel: 1.0
    acc: 10.0
human_init_variance: # [pos, vel, acc] for each human DoF
    pos: 10.0
    vel: 100.0
    acc: 1000.0
robot_init_variance: # [pos, vel, acc] for each robot DoF
    pos: 0.01
    vel: 0.1
    acc: 1.0
human_Kp: 1.0
human_Kd: 1.0
human_K_repulse: 1.0
robot_control_law: TRAJ_FOLLOW
robot_n_dof: 6
alpha: 0.3
beta: 2.0
kappa: 0.1
skeleton_topic: "/zed/zed_node/body_trk/skeletons"
robot_js_topic: "/ur10/joint_states"
predicted_hri_state_topic: "/predicted_hri_state"
predicted_hri_cov_topic: "/predicted_hri_cov"
human_state_topic: "/human_state"
camera_frame: "zed_camera_link"
world_frame: "world"
hz: 100
num_steps: 10