dt: 0.01
human_control_law: CONST_VEL
human_kynematic_model: KEYPOINTS
human_n_dof: 3
human_noisy: False
human_model_variances: [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1] # [pos, vel, acc] x human_n_dof
human_Kp: 1.0
human_Kd: 1.0
human_K_repulse: 1.0
robot_control_law: TRAJ_FOLLOW
robot_n_dof: 6
alpha: 0.3
beta: 2.0
kappa: 0.1
skeleton_topic: "/zed/zed_node/body_trk/skeletons"
robot_js_topic: "/robot/joint_states"
hz: 100
num_steps: 10