%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/galois/projects/estimation_ws/src/hri_predict_ros/logs/gui_data/gui_log_sub_0.txt
%
% Auto-generated by MATLAB on 28-May-2024 11:12:49

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Timestamp", "Task_name", "Velocity", "Instruction_id", "Instruction"];
opts.VariableTypes = ["datetime", "categorical", "categorical", "categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Task_name", "Velocity", "Instruction_id", "Instruction"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Timestamp", "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS", "DatetimeFormat", "preserveinput");

% Import the data
sub_0 = readtable("/home/galois/projects/estimation_ws/src/hri_predict_ros/logs/gui_data/gui_log_sub_0.txt", opts);
sub_1 = readtable("/home/galois/projects/estimation_ws/src/hri_predict_ros/logs/gui_data/gui_log_sub_1.txt", opts);
sub_2 = readtable("/home/galois/projects/estimation_ws/src/hri_predict_ros/logs/gui_data/gui_log_sub_2.txt", opts);
sub_3 = readtable("/home/galois/projects/estimation_ws/src/hri_predict_ros/logs/gui_data/gui_log_sub_3.txt", opts);
sub_4 = readtable("/home/galois/projects/estimation_ws/src/hri_predict_ros/logs/gui_data/gui_log_sub_4.txt", opts);
sub_5 = readtable("/home/galois/projects/estimation_ws/src/hri_predict_ros/logs/gui_data/gui_log_sub_5.txt", opts);
sub_6 = readtable("/home/galois/projects/estimation_ws/src/hri_predict_ros/logs/gui_data/gui_log_sub_6.txt", opts);

%% 
subs = {sub_0, sub_1, sub_2, sub_3, sub_4, sub_5, sub_6};
subs_names = ["sub_0", "sub_1", "sub_2", "sub_3", "sub_4", "sub_5", "sub_6"];

%% Clear temporary variables
clear opts

%% Subtract the time offset
for i=1:numel(subs)
    data = subs{i};
    
    idx_slow_pick = find((data.Task_name == 'PICK-&-PLACE') & ...
                    (data.Velocity == 'SLOW'));
    data.Timestamp(idx_slow_pick) = data.Timestamp(idx_slow_pick) - seconds(5); 

    idx_slow_walk = find((data.Task_name == 'WALKING') & ...
                    (data.Velocity == 'SLOW'));
    data.Timestamp(idx_slow_walk) = data.Timestamp(idx_slow_walk) - seconds(4); 

    idx_slow_pass = find((data.Task_name == 'PASSING-BY') & ...
                    (data.Velocity == 'SLOW'));
    data.Timestamp(idx_slow_pass) = data.Timestamp(idx_slow_pass) - seconds(10); 

    idx_medium_pick = find((data.Task_name == 'PICK-&-PLACE') & ...
                    (data.Velocity == 'MEDIUM'));
    data.Timestamp(idx_medium_pick) = data.Timestamp(idx_medium_pick) - seconds(3); 

    idx_medium_walk = find((data.Task_name == 'WALKING') & ...
                    (data.Velocity == 'MEDIUM'));
    data.Timestamp(idx_medium_walk) = data.Timestamp(idx_medium_walk) - seconds(3); 

    idx_medium_pass = find((data.Task_name == 'PASSING-BY') & ...
                    (data.Velocity == 'MEDIUM'));
    data.Timestamp(idx_medium_pass) = data.Timestamp(idx_medium_pass) - seconds(7); 

    idx_fast_pick = find((data.Task_name == 'PICK-&-PLACE') & ...
                    (data.Velocity == 'FAST'));
    data.Timestamp(idx_fast_pick) = data.Timestamp(idx_fast_pick) - seconds(1); 

    idx_fast_walk = find((data.Task_name == 'WALKING') & ...
                    (data.Velocity == 'FAST'));
    data.Timestamp(idx_fast_walk) = data.Timestamp(idx_fast_walk) - seconds(2); 

    idx_fast_pass = find((data.Task_name == 'PASSING-BY') & ...
                    (data.Velocity == 'FAST'));
    data.Timestamp(idx_fast_pass) = data.Timestamp(idx_fast_pass) - seconds(5);

    writetable(data,strcat('gui_log_',subs_names(i),'.txt'),'Delimiter',',')  

end

